# Generated by Django 3.0.6 on 2020-07-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20200730_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslink',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.Category'),
        ),
        migrations.AddField(
            model_name='movieslink',
            name='gen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.Genre'),
        ),
    ]
