# Generated by Django 3.0.6 on 2020-07-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20200730_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catgry',
            new_name='category',
        ),
    ]
